openapi: "3.0.0"
info:
  title: http4s Guardrail example
  version: 0.0.1
tags:
  - name: hello
paths:
  /hello:
    get:
      tags: [hello]
      x-scala-package: hello
      operationId: getHello
      summary: Returns a hello message
      responses:
        200:
          description: Hello message
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HelloResponse'

  /farewell:
    get:
      tags: [farewell]
      x-scala-package: farewell
      operationId: getFarewell
      summary: Returns a farewell message
      responses:
        200:
          description: Farewell message
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FarewellResponse'

components:
  schemas:
    HelloResponse:
      type: object
      properties:
        message:
          type: string
      required:
        - message

    FarewellResponse:
      type: object
      properties:
        message:
          type: string
      required:
        - message