openapi: "3.0.0"
info:
  title: DISTANCE API definition
  version: 0.0.1
tags:
  - name: dapi
paths:
  /example/{forename}/surname/{surname}:
    get:
      tags: [example]
      x-scala-package: example
      operationId: getExample
      summary: Returns an example message
      parameters:
        - name: forename
          in: path
          required: true
          description: the forename identifier, as personId
          schema:
            type: string
        - name: surname
          in: path
          required: true
          description: the surname identifier, as personId
          schema:
            type: string
      responses:
        200:
          description: Example message
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ExampleResponse'

components:

  securitySchemes:
    bearerAuth:            # arbitrary name for the security scheme
      type: http
      scheme: bearer
      bearerFormat: JWT    # optional, arbitrary value for documentation purposes
  # 2) Apply the security globally to all operations
  security:
    - bearerAuth: []

  parameters:
    IdParam:
      name: id
      in: query
      description: Id of object to return
      schema:
        type: integer
        format: int32

    IdParamOptional:
      name: id
      in: query
      description: Id of object to return
      required: false
      schema:
        type: integer
        format: int32

    NameParam:
      name: name
      in: query
      description: Name of object
      schema:
        type: string

    MaxItems:
      name: maxItems
      in: query
      description: Maximum items to be returned
      required: true
      schema:
        type: integer
        format: int32
        minimum: 100
        default: 5000

  schemas:

    DistancesResponse:
      type: object
      properties:
        count:
          type: integer
          format: int32
        distances:
          type: array
          items:
            type: object
            properties:
              cities:
                type: array
                items:
                  type: object
                  properties:
                    name:
                      type: string
                    coords:
                      type: string
              distance:
                type: integer
                format: int32
              units:
                type: string

    ExampleResponse:
      type: object
      properties:
        message:
          type: string
      required:
        - message