openapi: "3.0.0"
info:
  title: DPET API definition
  version: 0.0.1
tags:
  - name: hello
paths:
  /hello:
    get:
      tags: [hello]
      x-scala-package: hello
      operationId: getHello
      summary: Returns a hello message
      parameters:
        - $ref: '#/components/parameters/NameParam'
      responses:
        200:
          description: Hello message
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HelloResponse'

  /farewell/{forename}/surname/{surname}:
    get:
      tags: [farewell]
      x-scala-package: farewell
      operationId: getFarewell
      summary: Returns a farewell message
      parameters:
        - name: forename
          in: path
          required: true
          description: the forename identifier, as personId
          schema:
            type: string
        - name: surname
          in: path
          required: true
          description: the surname identifier, as personId
          schema:
            type: string
      responses:
        200:
          description: Farewell message
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FarewellResponse'

  /accounts:
    get:
      tags: [accounts]
      x-scala-package: accounts
      operationId: getAccounts
      summary: Returns a list of accounts
      responses:
        200:
          description: Accounts message
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AccountsResponse'

components:
  parameters:
    NameParam:
      name: name
      in: query
      description: Name to greet
      schema:
        type: string

  schemas:
    AccountsResponse:
      type: object
      properties:
        message:
          type: string
      required:
        - message

    HelloResponse:
      type: object
      properties:
        message:
          type: string
      required:
        - message

    FarewellResponse:
      type: object
      properties:
        message:
          type: string
      required:
        - message