openapi: "3.0.0"
info:
  title: DPET API definition
  version: 0.0.1
tags:
  - name: dpet
paths:
  /example/{forename}/surname/{surname}:
    get:
      tags: [example]
      x-scala-package: example
      operationId: getExample
      summary: Returns an example message
      parameters:
        - name: forename
          in: path
          required: true
          description: the forename identifier, as personId
          schema:
            type: string
        - name: surname
          in: path
          required: true
          description: the surname identifier, as personId
          schema:
            type: string
      responses:
        200:
          description: Example message
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ExampleResponse'

  /divisions:
    get:
      tags: [divisions]
      x-scala-package: divisions
      operationId: getDivisions
      summary: Returns a list of divisions or a division by id
      parameters:
        - $ref: '#/components/parameters/IdParam'
        - $ref: '#/components/parameters/NameParam'
        - $ref: '#/components/parameters/PageNumberParam'
        - $ref: '#/components/parameters/PageSizeParam'
      responses:
        200:
          description: Divisions message
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DivisionsResponse'
        404:
          description: No Divisions Found

  /wms/inventory:
    get:
      tags: [inventory]
      x-scala-package: inventory
      operationId: getWmsInventory
      summary: Returns a list of inventory or a inventory by gtin
      parameters:
        - $ref: '#/components/parameters/GtinParam'
        - $ref: '#/components/parameters/WarehouseParam'
        - $ref: '#/components/parameters/PageNumberParam'
        - $ref: '#/components/parameters/PageSizeParam'
      responses:
        200:
          description: Inventory message
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InventoryResponse'
        404:
          description: No Inventory Found

components:
  parameters:

    NameParam:
      name: name
      in: query
      description: Name of object
      schema:
        type: string
    IdParam:
      name: id
      in: query
      description: Id of object to return
      schema:
        type: integer
        format: int32

    WarehouseParam:
      name: warehouse
      in: query
      description: Code for warehouse, e.g. IT-BO-BSL
      schema:
        type: string
        enum: [IT-BO-BSL, US-NJ-PLG, GB-LN-DC1, US-NJ-DC2, IT-MI-DC4, JP-YOK-YAMATO, HK-TM-LIFESTYLE, CN-SH-LIFESTYLE, UAE-DU-LIBERTY]
      examples:
        -sample1:
          value:
            name: IT-BO-BSL
        -sample2:
          value:
            name: GB-LN-DC1

    GtinParam:
      name: gtin
      in: query
      description: One or more GTINs
      required: true
      schema:
        type: array
        items:
          type: string
          pattern: '^\d{14}$'
        uniqueItems: true
      examples:
        oneGTINs:
          summary: Example of a single GTIN
          value: ["04005009669892"]   # ?gtin=04005009669892
        multipleGTINs:
          summary: Example of multiple GTINs
          value: ["0400500966989","0400463499234","0400504063233"]   # ?gtin=0400463499234&gtin=0400463499234&gtin=0400504063233

    PageNumberParam:
      name: pageNumber
      in: query
      description: Page Number
      schema:
        type: integer
        format: int32
        minimum: 1
        default: 1

    PageSizeParam:
      name: pageSize
      in: query
      description: Page Size
      schema:
        type: integer
        format: int32
        minimum: 1
        maximum: 500
        default: 25

  schemas:

    DivisionsResponse:
      type: object
      properties:
        count:
          type: integer
          format: int32
        divisions:
          type: array
          items:
            type: object
            properties:
              id:
                type: string
              name:
                type: string
              shortname:
                type: string
              active:
                type: boolean

    InventoryResponse:
      type: object
      properties:
        count:
          type: integer
          format: int32
        warehouse:
          type: string
        inventory:
          type: array
          items:
            type: object
            properties:
              gtin:
                type: string
              supply:
                type: integer
                format: int32

    ExampleResponse:
      type: object
      properties:
        message:
          type: string
      required:
        - message