openapi: "3.0.0"
info:
  title: DISTANCE API definition
  version: 0.0.1
tags:
  - name: dapi
paths:

  /distance:
    get:
      tags: [gps]
      x-scala-package: distance
      operationId: getDistance
      summary: Returns a distance calculation message
      parameters:
        - $ref: '#/components/parameters/CityParam'
        - $ref: '#/components/parameters/UnitsParam'
      responses:
        200:
          description: Distance result
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DistanceResponse'

components:

  parameters:

    CityParam:
      name: city
      in: query
      description: One or more cities, mimimum 2 required.
      required: true
      schema:
        type: array
        items:
          type: string
          pattern: '^[a-zA-Z]{3,}$'  # At least 3 alpha characters
          minLength: 3
          maxLength: 20
        minItems: 2
        maxItems: 2
        uniqueItems: true
      examples:
        oneCity:
          summary: Example of one city (2 are required to generate a distance)
          value: ["Summertown"]
        multipleCities:
          summary: Example of multiple cities (only first 2 will be used)
          value: ["Summertown","Qutyini","Osgiliath"]

    UnitsParam:
      name: units
      in: query
      description: Code for distance units to be used in calculating the distance between the cities
      required: false
      schema:
        type: string
        enum: ["KM", "SMI", "NMI"]
        default: "KM"

    MaxItems:
      name: maxItems
      in: query
      description: Maximum items to be returned
      required: true
      schema:
        type: integer
        format: int32
        minimum: 100
        default: 5000

    PageNumberParam:
      name: pageNumber
      in: query
      description: Page Number
      schema:
        type: integer
        format: int32
        minimum: 1
        default: 1

    PageSizeParam:
      name: pageSize
      in: query
      description: Page Size
      schema:
        type: integer
        format: int32
        minimum: 1
        maximum: 500
        default: 200

  schemas:

    DistanceResponse:
      type: object
      properties:
        count:
          type: integer
          format: int32
        units:
          type: string
        total:
          type: number
        distances:
          type: array
          items:
            type: object
            properties:
              cities:
                type: array
                items:
                  type: object
                  properties:
                    name:
                      type: string
                    coords:
                      type: string
              distance:
                type: number
              units:
                type: string
