openapi: "3.0.0"
info:
  title: DPET API definition
  version: 0.0.1
tags:
  - name: dpet
paths:
  /example/{forename}/surname/{surname}:
    get:
      tags: [example]
      x-scala-package: example
      operationId: getExample
      summary: Returns an example message
      parameters:
        - name: forename
          in: path
          required: true
          description: the forename identifier, as personId
          schema:
            type: string
        - name: surname
          in: path
          required: true
          description: the surname identifier, as personId
          schema:
            type: string
      responses:
        200:
          description: Example message
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ExampleResponse'

  /divisions:
    get:
      tags: [divisions]
      x-scala-package: divisions
      operationId: getDivisions
      summary: Returns a list of divisions or a division by id
      parameters:
        - $ref: '#/components/parameters/IdParam'
        - $ref: '#/components/parameters/NameParam'
        - $ref: '#/components/parameters/PageNumberParam'
        - $ref: '#/components/parameters/PageSizeParam'
      responses:
        200:
          description: Divisions message
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DivisionsResponse'
        404:
          description: No Divisions Found

components:
  parameters:
    NameParam:
      name: name
      in: query
      description: Name of object
      schema:
        type: string
    IdParam:
      name: id
      in: query
      description: Id of object to return
      schema:
        type: integer
        format: int32
    PageNumberParam:
      name: pageNumber
      in: query
      description: Page Number
      schema:
        type: integer
        format: int32
        minimum: 1
        default: 1
    PageSizeParam:
      name: pageSize
      in: query
      description: Page Size
      schema:
        type: integer
        format: int32
        minimum: 1
        maximum: 500
        default: 25

  schemas:
    DivisionsResponse:
      type: object
      properties:
        count:
          type: integer
          format: int32
        divisions:
          type: array
          items:
            type: object
            properties:
              id:
                type: string
              name:
                type: string
              shortname:
                type: string
              active:
                type: boolean

    ExampleResponse:
      type: object
      properties:
        message:
          type: string
      required:
        - message